### ISSUE TITLE
Illegal instruction (core dumped) no matter dev or docker install

### ISSUE THREAD

**Issue by JugglerLKR** [teableio/teable#1154]
After installing either from github or using docker app crashes with error
Illegal instruction (core dumped)

Teable v1.5.2 (or Docker standalone version from exmples)

Ubuntu 24.04.1 LTS

![1](https://github.com/user-attachments/assets/db4349f5-dc00-472d-b788-9a2fbb631257)
![2](https://github.com/user-attachments/assets/b5c61948-52e7-4ec7-a563-1deace5f44be)

**Comment by tea-artist** [comment]
This is usually due to incompatible chip architectures.
You can execute the following code to provide specific information.
```bash
# Check Node.js version
node --version

# Check npm version
npm --version

# Verify architecture
node -p "process.arch"
```

**Comment by JugglerLKR** [comment]
> This is usually due to incompatible chip architectures. You can execute the following code to provide specific information.

It is x64 Ubuntu - nothing special, not arm

node --version
v22.12.0

npm --version
10.9.2

node -p "process.arch"
x64

**Comment by tea-artist** [comment]
This is most likely a CPU compatibility issue.

1. Check your CPU capabilities:
```bash
cat /proc/cpuinfo | grep flags
```
Look for: SSE4.2, AVX, AVX2

2. Check if you're running on:
- An old CPU
- A low-end VPS/Cloud instance
- A virtual machine with limited CPU features

Solutions:
- If on VPS/Cloud: Upgrade to a higher-tier instance with modern CPU features
- If on VM: Enable required CPU features in virtualization settings
- If on old hardware: Consider upgrading hardware or using an older version of the application

**Comment by tea-artist** [comment]
Node.js CPU support changes:

1. Node.js v12 and earlier:
- Minimum: SSE2 instruction set
- Supports most x64 processors since 2003

2. Node.js v14 and later:
- Minimum: SSE4.2 instruction set (introduced ~2008)
- Dropped support for older CPUs
- Affects Intel processors before Nehalem (2008)
- Affects AMD processors before Bulldozer (2011)

3. V8 engine (which Node.js uses) requirements:
- SSE4.2 is mandatory since V8 v8.0
- AVX may be required for some operations in newer versions

Your CPU likely lacks SSE4.2 support.

**Comment by JugglerLKR** [comment]
> * Minimum: SSE4.2 instruction set (introduced ~2008)
> 
> * Dropped support for older CPUs
> 
> * Affects Intel processors before Nehalem (2008)
> 
> * Affects AMD processors before Bulldozer (2011)

thanks. got it. problem lies in old cpu.
