### ISSUE TITLE
[Feature Request] Duplicate Views

### ISSUE THREAD

**Issue by solankimihir** [teableio/teable#586]
**Is your feature request related to a problem? Please describe.**
No. Feature request is not related to a problem.

**Describe the solution you'd like**
I would like to create duplicate of existing views. I have monthly tasks that I create for my team. For creating 1 view, I have to apply multiple nested filters. I am creating 1 view for each of my team member. The only difference in filter criteria for each of this view is that I 
change the "Mapped To" user from "Team Member 1" to "Team Member 2".

It would be great if I can duplicate the view created for Team Member 1 and in the duplicated view just change the filter of "Mapped To" from "Team member 1" to "Team member 2". 

**Describe alternatives you've considered**
None. Currently I need to define all filter-criteria from scratch for each team-member view.

**Additional context**
None.

**Comment by tea-artist** [comment]
We'll make it happen when the time is right

**Comment by Virajjai** [comment]
Hi @solankimihir @tea-artist , I would like to contribute to it so could you please explain me little bit more and help me out from where to start.

**Comment by solankimihir** [comment]
Basically, if I have a view created in teable with multiple filters, groupings etc. then I want to be able to duplicate the view into a new one.

Example:
Current view with filters and groupings configured:
![image](https://github.com/user-attachments/assets/24f4a521-9307-48fa-bc7c-5a2863637aea)



I want an option to create a new view with same filter and groupings (so that I can modify it further)
![image](https://github.com/user-attachments/assets/c06109db-7999-43c7-bcbb-1bba5a864df4)

**Comment by Virajjai** [comment]
Ohhh, got it and thanks for elaborating ,@solankimihir  could you please tell me the stating point in code base from where i can start.

**Comment by Virajjai** [comment]
Hi there, I'm new open source contributor so please could help me out and guide me for this I'm trying to figure out from where to start and firstly what to do .

**Comment by tea-artist** [comment]
Hi @Virajjai  Thank you for your contribution to our open-source project. Here's a response addressing the development of the view duplication feature:

To implement the view duplication functionality, you can utilize the existing 'create view' API. This API supports specifying any view attributes during the creation process. For detailed parameter definitions, please refer to the file located at `packages/openapi/src/view/create.ts`.

To access all view properties, you can use the `useView` hook from our SDK. When duplicating a view, it's important to focus on copying only the attributes that control the view's display, such as `columnMeta`, `filter`, `sort`, and `group`. Please note that these attributes may vary slightly for different view types, particularly due to `columnMeta`. For precise details, you'll need to consult the source code.

For API e2e testing:
1. First, run `pnpm test-e2e` in the backend directory to initialize the testing environment.
2. Once successful, add the duplication test logic to the `apps/nestjs-backend/test/view.e2e-spec.ts` file.
3. Execute the test using the command: `pnpm test-e2e apps/nestjs-backend/test/view.e2e-spec.ts`.

Regarding the frontend UI:
The duplicate button should only be displayed when the user has `view|create` permissions. During the creation process, ensure that the necessary checks and validations are in place.

If you need any further clarification or assistance, please don't hesitate to ask. We appreciate your efforts in contributing to our project!

**Comment by Virajjai** [comment]
Thank you @tea-artist  for the detailed explanation! I'll start implementing the duplication feature using the create view API and focus on the key attributes for display. I'll also make sure to handle the frontend UI and permission checks as suggested. If I encounter any issues or need further clarification, I'll reach out. Thanks again for the support!
