### ISSUE TITLE
mysql alternatvie

### ISSUE THREAD

**Issue by Drjuror** [teableio/teable#751]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Drjuror** [comment]
can i use mysql not pg instead?

**Comment by mmospanenko** [comment]
please, no)

**Comment by kpodp0ra** [comment]
Related: #832

**Comment by decky-grande** [comment]
I think what is needed is the capability to install self-hosted using MySQL/MariaDB instead of Postgress,
I tried to use MySQL image as a database and modify the ENV, but there is an Application level error where the Prisma connection uses a hard-coded constant string "postgresql"


```
PrismaClientInitializationError: 
Invalid `prisma.attachments.upsert()` invocation:
error: Error validating datasource `db`: the URL must start with the protocol `postgresql://` or `postgres://`.

  -->  schema.prisma:9
   | 
 8 |   provider = "postgres"
 9 |   url      = env("PRISMA_DATABASE_URL")
   | 
```

**Comment by kpodp0ra** [comment]
@decky-grande I see what you were going for, but unfortunately, it’s not that straightforward. The application was designed with multiple databases in mind, and each database is handled in a modular way through separate files. This means that adding support for another database, like MySQL/MariaDB, is definitely possible. That said, it’s not something that can be done instantly—it requires careful implementation to ensure everything works seamlessly. Simply swapping “postgres” for “mysql” in the schema won’t work because there’s a lot happening under the hood that depends on PostgreSQL.
